### ISSUE TITLE
bug: \r in parsed data when \r\n is used as newline character

### ISSUE THREAD

**Issue by omstaendlig** [Lookyloo/pysecuritytxt#83]
For instance, the [security.txt file of Bokio.se](https://www.bokio.se/.well-known/security.txt) uses CR+LF as a newline character, which results in trailing \r in every parsed value.

`pysecuritytxt bokio.se --parse`

![image](https://github.com/user-attachments/assets/0ac47411-8ae8-437a-80ec-5895ba71ad43)

**Comment by Rafiot** [comment]
Good catch! Release incoming.
